apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dn2pql476-python 
  janus-idp.io/tekton: dn2pql476-python
  backstage.io/kubernetes-id: dn2pql476-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dn2pql476-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml