apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dn2pql476-python
  janus-idp.io/tekton: dn2pql476-python
  backstage.io/kubernetes-id: dn2pql476-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dn2pql476-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
