apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dn2pql476-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dn2pql476-python 
  name: dn2pql476-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dn2pql476-python 
